//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MPEntities : DbContext
    {
        public MPEntities()
            : base("name=MPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MST_Cart> MST_Cart { get; set; }
        public virtual DbSet<TBL_Order_Detail> TBL_Order_Detail { get; set; }
        public virtual DbSet<TBL_Order_MST> TBL_Order_MST { get; set; }
        public virtual DbSet<tblCities> tblCities { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblRole> tblRole { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
