//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Cart
    {
        public int id { get; set; }
        public int User_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
