//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Order_Detail
    {
        public int ID { get; set; }
        public int Order_ID { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual TBL_Order_MST TBL_Order_MST { get; set; }
    }
}
