//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Order_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Order_MST()
        {
            this.TBL_Order_Detail = new HashSet<TBL_Order_Detail>();
        }
    
        public int Order_ID { get; set; }
        public string Order_No { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> GstAmount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> PayableAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Order_Detail> TBL_Order_Detail { get; set; }
        public virtual TBL_Order_MST TBL_Order_MST1 { get; set; }
        public virtual TBL_Order_MST TBL_Order_MST2 { get; set; }
    }
}
