//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCities
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
    }
}
