//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productid { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
    }
}
