//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contactno { get; set; }
        public Nullable<int> gender { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> countryid { get; set; }
        public string profilepicture { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public Nullable<bool> isloginallowed { get; set; }
        public Nullable<bool> isemailverified { get; set; }
    }
}
